version: '3.9'

services:
  # Единый инстанс БД для экономии ресурсов (внутри создадим 2 базы)
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5

  # Сервис Платежей
  payment_service:
    build: ./payment_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@postgres/payments_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # Сервис Заказов
  order_service:
    build: ./order_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@postgres/orders_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # API Gateway + Frontend Host
  gateway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - order_service
      - payment_service